# Generated by Django 4.2.30 on 2026-08-31 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserClientLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada'), ('REVOKED', 'Revocada')], default='PENDING', max_length=10, verbose_name='Estado')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo del rechazo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_links', to='clientes.cliente', verbose_name='Cliente')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_client_links', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_links', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Vinculación usuario-cliente',
                'verbose_name_plural': 'Vinculaciones usuario-cliente',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='userclientlink',
            constraint=models.UniqueConstraint(fields=('user', 'client'), name='unique_user_client_link'),
        ),
    ]
