# Generated by Django 4.2.30 on 2026-09-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda_origen', models.CharField(max_length=10)),
                ('moneda_destino', models.CharField(max_length=10)),
                ('tasa_compra', models.DecimalField(decimal_places=4, max_digits=12)),
                ('tasa_venta', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
