# Generated by Django 4.2.30 on 2026-08-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_razon_social', models.CharField(max_length=255, verbose_name='Nombre o Razón Social')),
                ('documento', models.CharField(max_length=50, unique=True, verbose_name='RUC o CI')),
                ('tipo_persona', models.CharField(choices=[('FISICA', 'Persona Física'), ('JURIDICA', 'Persona Jurídica')], default='FISICA', max_length=10)),
                ('categoria', models.CharField(choices=[('A', 'Categoría A - Premium'), ('B', 'Categoría B - Estándar'), ('C', 'Categoría C - Riesgo Alto')], default='B', max_length=1)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]