# Generated by Django 4.2.30 on 2026-09-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_unique_active_cliente_per_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='customer_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Identificador de cliente'),
        ),
    ]
