# Generated by Django 4.2.30 on 2026-09-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='customer_id',
        ),
    ]
