# Generated by Django 4.2.30 on 2026-09-09 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: USD, PYG, BRL', max_length=5, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('simbolo', models.CharField(help_text='Ej: $, ₲, R$', max_length=5)),
                ('activa', models.BooleanField(default=True, help_text='Habilitada en el sistema')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_compra', models.DecimalField(decimal_places=4, max_digits=12)),
                ('tasa_venta', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasas', to='divisas.moneda')),
                ('usuario_modificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
