# Generated by Django 4.2.30 on 2026-08-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre o razón social')),
                ('document_number', models.CharField(max_length=30, unique=True, verbose_name='Número de documento')),
                ('person_type', models.CharField(choices=[('PHYSICAL', 'Persona Física'), ('LEGAL', 'Persona Jurídica')], max_length=10, verbose_name='Tipo de persona')),
                ('category', models.CharField(choices=[('RETAIL', 'Minorista'), ('CORPORATE', 'Corporativo'), ('VIP', 'VIP')], default='RETAIL', max_length=10, verbose_name='Categoría')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Cliente verificado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
    ]
