# Generated by Django 4.2.30 on 2026-09-11 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0006_cliente_stripe_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_method_id', models.CharField(max_length=100, unique=True, verbose_name='Identificador del método en Stripe')),
                ('alias', models.CharField(blank=True, max_length=100, verbose_name='Alias')),
                ('marca', models.CharField(blank=True, max_length=30, verbose_name='Marca')),
                ('ultimos_cuatro', models.CharField(blank=True, max_length=4, verbose_name='Últimos cuatro dígitos')),
                ('mes_vencimiento', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mes de vencimiento')),
                ('anio_vencimiento', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año de vencimiento')),
                ('predeterminado', models.BooleanField(default=False, verbose_name='Método predeterminado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medios_pago', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Medio de pago',
                'verbose_name_plural': 'Medios de pago',
                'ordering': ['-predeterminado', '-fecha_creacion'],
            },
        ),
    ]
