# Generated by Django 4.2.30 on 2026-09-11 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_remove_cliente_customer_id'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREDITO', 'Tarjeta de crédito'), ('DEBITO', 'Tarjeta de débito'), ('BILLETERA', 'Billetera electrónica')], max_length=20, verbose_name='Tipo de medio de pago')),
                ('alias', models.CharField(help_text='Ejemplo: Tarjeta personal', max_length=100, verbose_name='Alias')),
                ('titular', models.CharField(max_length=150, verbose_name='Nombre del titular')),
                ('marca', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('AMEX', 'American Express'), ('OTRA', 'Otra')], max_length=20, verbose_name='Marca')),
                ('ultimos_cuatro', models.CharField(max_length=4, verbose_name='Últimos cuatro dígitos')),
                ('mes_vencimiento', models.PositiveSmallIntegerField(verbose_name='Mes de vencimiento')),
                ('anio_vencimiento', models.PositiveSmallIntegerField(verbose_name='Año de vencimiento')),
                ('predeterminado', models.BooleanField(default=False, verbose_name='Medio predeterminado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medios_pago', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Medio de pago',
                'verbose_name_plural': 'Medios de pago',
                'ordering': ['-predeterminado', '-fecha_creacion'],
            },
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
